apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-init
  namespace: netology
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: init
  template:
    metadata:
      labels:
        app: init
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      initContainers:
      - name: busybox
        image: busybox
        command: ['sleep', '30']
