apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: netology
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:latest
      - name: multitool
        image: praqma/network-multitool
        env:
          - name: HTTP_PORT
            value: "1800"
