stages:
  - build
  - deploy
image: docker:cli
services:
  - docker:dind
variables:
  DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  REGISTRY: registry.gitlab.com
  PROJECT_NAME: Zhivarev/diplom-nginx

build-tag:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  rules:
  - if: $CI_COMMIT_TAG =~ /^v\d+.\d+/

build-branch:
  stage: build
  script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY -u $CI_REGISTRY_USER --password-stdin
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: ['']
  script:
    - kubectl config get-contexts
    - kubectl config use-context Zhivarev/diplom-nginx:diplom-agent
    - kubectl set image deployment web *=$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - kubectl rollout restart deployment/web -n default
  rules:
  - if: $CI_COMMIT_TAG =~ /^v\d+.\d+/