stages:
  - build
  - deploy
image: docker:20.10.5
services:
  - docker:20.10.5-dind
builder:
  stage: build
  script:
    - docker build --pull -t some_local_build:latest .
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d+.\d+/

deployer:
  stage: deploy
  script:
    - docker build -t $CI_REGISTRY/zhivarev/diplom-nginx/diplom-nginx:latest .
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push $CI_REGISTRY/zhivarev/diplom-nginx/diplom-nginx:latest
  rules:
  - if: $CI_COMMIT_BRANCH
    exists:
    - Dockerfile
